/**
 * Pre-built marker images for Android Google Maps.
 * Android's custom view → bitmap rendering is unreliable, so we use
 * static PNG images via the Marker `image` prop instead.
 * iOS uses custom React Native views directly (no issue there).
 *
 * Generated by: scripts/generate-marker-images.cjs
 */
import { Platform } from 'react-native';
import type { ImageURISource } from 'react-native';

type MarkerImage = number | ImageURISource;

// Only load on Android to avoid unnecessary imports on iOS
const isAndroid = Platform.OS === 'android';

// Trail difficulty markers (colored circles with white border)
const TRAIL_IMAGES: Record<string, MarkerImage> = isAndroid ? {
  easy: require('../../assets/markers/trail-easy.png'),
  moderate: require('../../assets/markers/trail-moderate.png'),
  hard: require('../../assets/markers/trail-hard.png'),
  expert: require('../../assets/markers/trail-expert.png'),
  unknown: require('../../assets/markers/trail-unknown.png'),
} : {};

const TRAIL_SELECTED_IMAGES: Record<string, MarkerImage> = isAndroid ? {
  easy: require('../../assets/markers/trail-easy-selected.png'),
  moderate: require('../../assets/markers/trail-moderate-selected.png'),
  hard: require('../../assets/markers/trail-hard-selected.png'),
  expert: require('../../assets/markers/trail-expert-selected.png'),
  unknown: require('../../assets/markers/trail-unknown-selected.png'),
} : {};

// Park markers (badge shapes for NP/SP, diamond for other national sites)
const PARK_IMAGES = isAndroid ? {
  national: require('../../assets/markers/park-national.png'),
  state: require('../../assets/markers/park-state.png'),
  other: require('../../assets/markers/park-other.png'),
} : { national: undefined, state: undefined, other: undefined };

// Campground marker (tent shape)
const CAMPGROUND_IMAGE = isAndroid
  ? require('../../assets/markers/campground.png')
  : undefined;

/**
 * Get the marker image for a trail based on its normalized difficulty.
 * Returns undefined on iOS (custom views used instead).
 */
export function getTrailMarkerImage(
  normalizedDifficulty: string,
  isSelected: boolean,
): MarkerImage | undefined {
  if (!isAndroid) return undefined;
  const key = normalizedDifficulty || 'unknown';
  return isSelected
    ? TRAIL_SELECTED_IMAGES[key] || TRAIL_SELECTED_IMAGES.unknown
    : TRAIL_IMAGES[key] || TRAIL_IMAGES.unknown;
}

/**
 * Get the marker image for a park.
 * Three-way classification: NP badge (brown), SP badge (green), other diamond (gray).
 * Returns undefined on iOS (custom views used instead).
 */
export function getParkMarkerImage(isNP: boolean, isState: boolean): MarkerImage | undefined {
  if (!isAndroid) return undefined;
  if (isNP) return PARK_IMAGES.national;
  if (isState) return PARK_IMAGES.state;
  return PARK_IMAGES.other;
}

/**
 * Get the marker image for a campground.
 * Returns undefined on iOS.
 */
export function getCampgroundMarkerImage(): MarkerImage | undefined {
  return CAMPGROUND_IMAGE;
}
