/**
 * Park-specific features for photo searches
 * Maps park codes to notable features, attractions, and activities
 */

export const PARK_FEATURES: Record<string, string[]> = {
  'acad': ['Cadillac Mountain sunrise', 'rocky coastline', 'Bass Harbor lighthouse'],
  'arch': ['Delicate Arch', 'Landscape Arch', 'Fiery Furnace'],
  'badl': ['badlands formations', 'prairie wildlife', 'night sky stars'],
  'bibe': ['Chisos Mountains', 'Rio Grande river', 'desert wildlife'],
  'bisc': ['coral reef snorkeling', 'mangroves', 'island kayaking'],
  'blca': ['canyon overlook', 'Painted Wall', 'Gunnison River'],
  'brca': ['Bryce Canyon hoodoos', 'Thor\'s Hammer', 'Navajo Loop Trail'],
  'cany': ['Island in the Sky', 'Mesa Arch sunrise', 'Needles District'],
  'care': ['Waterpocket Fold', 'Capitol Dome', 'petroglyphs'],
  'cave': ['Carlsbad Caverns underground', 'bat flight', 'cave formations'],
  'chis': ['island wildlife', 'sea caves kayaking', 'whale watching'],
  'cong': ['cypress swamp', 'boardwalk trail', 'fireflies'],
  'crla': ['Crater Lake blue water', 'Wizard Island', 'Rim Drive'],
  'cuva': ['Brandywine Falls', 'covered bridges', 'fall foliage'],
  'dena': ['Denali mountain peak', 'grizzly bears', 'northern lights'],
  'deva': ['Death Valley sand dunes', 'Badwater Basin salt flats', 'Artists Palette'],
  'drto': ['Fort Jefferson', 'snorkeling coral', 'sea turtles'],
  'ever': ['alligators wildlife', 'mangrove kayaking', 'bird watching'],
  'gaar': ['arctic wilderness', 'caribou migration', 'midnight sun'],
  'jeff': ['Gateway Arch', 'St Louis skyline', 'riverfront'],
  'glac': ['Going to the Sun Road', 'mountain goats', 'alpine lakes'],
  'glba': ['tidewater glaciers', 'whale watching', 'kayaking'],
  'grba': ['Lehman Caves', 'bristlecone pines', 'Wheeler Peak'],
  'grca': ['Colorado River rafting', 'South Rim viewpoint', 'Bright Angel Trail'],
  'grsa': ['sand dunes sunset', 'Medano Creek', 'alpine lakes'],
  'grsm': ['Cades Cove wildlife', 'Appalachian Trail', 'mountain streams'],
  'grte': ['Teton Range reflection', 'Jenny Lake', 'moose wildlife'],
  'gumo': ['El Capitan peak', 'McKittrick Canyon fall colors', 'desert trails'],
  'hale': ['Haleakala sunrise', 'volcanic crater', 'silversword plants'],
  'havo': ['Kilauea volcano', 'lava flows', 'volcanic crater'],
  'hosp': ['historic bathhouses', 'hot springs', 'Bathhouse Row'],
  'indu': ['Lake Michigan beach', 'sand dunes', 'Chicago skyline'],
  'isro': ['island wilderness', 'moose', 'lighthouse'],
  'jotr': ['Joshua trees desert', 'rock climbing boulders', 'Cholla Cactus Garden', 'Keys View sunset'],
  'katm': ['brown bears fishing', 'Brooks Falls', 'Valley of Ten Thousand Smokes'],
  'kefj': ['Exit Glacier', 'fjords boat tour', 'sea lions'],
  'kova': ['Kobuk sand dunes', 'caribou', 'arctic wilderness'],
  'lacl': ['volcanic landscape', 'brown bears', 'remote wilderness'],
  'lavo': ['Bumpass Hell', 'volcanic features', 'Lassen Peak'],
  'maca': ['Mammoth Cave underground', 'cave formations', 'Green River'],
  'meve': ['cliff dwellings', 'Cliff Palace', 'ancient pueblos'],
  'mora': ['Mount Rainier peak', 'wildflower meadows', 'Paradise'],
  'neri': ['New River Gorge Bridge', 'whitewater rafting', 'rock climbing'],
  'noca': ['North Cascades mountains', 'Diablo Lake', 'glaciers'],
  'olym': ['Hoh Rainforest', 'Hurricane Ridge', 'tide pools'],
  'pefo': ['petrified wood', 'Painted Desert', 'ancient fossils'],
  'pinn': ['rock spires', 'California condors', 'talus caves'],
  'redw': ['giant redwood trees', 'Fern Canyon', 'foggy forest'],
  'romo': ['elk wildlife', 'alpine tundra', 'Trail Ridge Road'],
  'sagu': ['saguaro cactus forest', 'desert sunset', 'Sonoran Desert'],
  'seki': ['Giant Sequoia trees', 'Moro Rock', 'Crystal Cave'],
  'shen': ['Skyline Drive', 'Blue Ridge Mountains', 'fall foliage'],
  'thro': ['badlands formations', 'wild horses', 'prairie'],
  'viis': ['tropical beaches', 'snorkeling coral reef', 'Trunk Bay'],
  'voya': ['lakes canoeing', 'northern lights', 'houseboating'],
  'whsa': ['white sand dunes', 'gypsum desert', 'sunset'],
  'wica': ['Wind Cave underground', 'boxwork formations', 'bison prairie'],
  'wrst': ['massive glaciers', 'mountain wilderness', 'Kennecott mines'],
  'yell': ['Old Faithful geyser', 'Yellowstone bison wildlife', 'Grand Prismatic Spring'],
  'yose': ['Half Dome', 'Yosemite Falls', 'El Capitan climbing'],
  'zion': ['Angels Landing', 'The Narrows hiking', 'Zion Canyon'],
};
